"""End-to-end application orchestration for audit/fix flows."""

from __future__ import annotations

import json
import tempfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd

from src.generate.inplace_formatter import audit_or_format_docx
from src.inference.artifact_registry import (
    BaselineArtifactBundle,
    TransformerArtifactBundle,
    find_latest_baseline_artifacts,
    find_latest_transformer_artifacts,
)
from src.inference.baseline_inferencer import run_baseline_inference
from src.inference.document_loader import DocumentInput, validate_document_input
from src.inference.pdf_loader import PdfNoTextLayer, check_text_layer, extract_pdf_blocks
from src.inference.transformer_inferencer import load_transformer_artifacts, run_transformer_inference
from src.io.block_extractor import extract_blocks_from_docx
from src.rules.profile_loader import PROFILES_DIR, list_available_profiles


PROJECT_ROOT = Path(__file__).resolve().parents[2]
RESULTS_DIR = PROJECT_ROOT / "results"
PREDICTIONS_DIR = RESULTS_DIR / "predictions"
REPORTS_DIR = RESULTS_DIR / "reports"
EXTRACTED_DIR = RESULTS_DIR / "extracted_blocks"
GENERATED_DOCX_DIR = RESULTS_DIR / "generated_docx"
GENERATED_PROFILES_DIR = RESULTS_DIR / "generated_profiles"


@dataclass(slots=True)
class ProcessingArtifacts:
    """Paths and data generated by one processing run."""

    model_type: str
    mode: str
    profile_path: Path
    input_path: Path
    input_extension: str          # ".docx" or ".pdf" — gates render_report badge + DOCX download (07-UI-SPEC D-04)
    extracted_csv: Path
    predictions_csv: Path
    report_csv: Path
    report_json: Path
    summary_json: Path
    summary_txt: Path
    output_docx: Path | None
    predictions_df: pd.DataFrame
    report_df: pd.DataFrame
    summary: dict[str, Any]


def ensure_runtime_directories() -> None:
    """Ensure output directories exist."""
    for path in [RESULTS_DIR, PREDICTIONS_DIR, REPORTS_DIR, EXTRACTED_DIR, GENERATED_DOCX_DIR]:
        path.mkdir(parents=True, exist_ok=True)


def list_model_options() -> dict[str, str]:
    """Return UI-friendly model options."""
    options = {}
    if find_latest_baseline_artifacts() is not None:
        options["baseline"] = "Baseline"
    else:
        options["baseline_unavailable"] = "Baseline (unavailable: no saved artifact)"
    options["transformer"] = "Transformer"
    return options


def get_profile_options() -> list[dict[str, str]]:
    """Return available GOST profiles."""
    return list_available_profiles([PROFILES_DIR, GENERATED_PROFILES_DIR])


def save_uploaded_bytes(data: bytes, suffix: str) -> Path:
    """Persist uploaded file bytes to a temporary path."""
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
        tmp.write(data)
        return Path(tmp.name)


def _timestamp() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def _render_summary_text(summary: dict[str, Any], model_type: str, mode: str) -> str:
    """Build a concise human-readable summary."""
    return "\n".join(
        [
            "GOST Processing Summary",
            f"model_type: {model_type}",
            f"mode: {mode}",
            f"profile_name: {summary.get('profile_name')}",
            f"blocks_total: {summary.get('blocks_total')}",
            f"no_change: {summary.get('no_change')}",
            f"review: {summary.get('review')}",
            f"changed: {summary.get('changed')}",
            f"error: {summary.get('error')}",
            f"blocked_unsafe_autofix: {summary.get('blocked_unsafe_autofix')}",
            f"output_docx: {summary.get('output_docx')}",
        ]
    )


def _save_run_sidecars(
    timestamp: str,
    report_df: pd.DataFrame,
    summary: dict[str, Any],
) -> tuple[Path, Path, Path]:
    """Persist JSON sidecars and text summary."""
    report_json = REPORTS_DIR / f"audit_report_{timestamp}.json"
    summary_json = REPORTS_DIR / f"summary_{timestamp}.json"
    summary_txt = REPORTS_DIR / f"summary_{timestamp}.txt"

    report_json.write_text(
        report_df.to_json(orient="records", force_ascii=False, indent=2),
        encoding="utf-8",
    )
    summary_json.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    summary_txt.write_text(
        _render_summary_text(summary=summary, model_type=summary["model_type"], mode=summary["mode"]),
        encoding="utf-8",
    )

    return report_json, summary_json, summary_txt


def _run_model_inference(
    model_choice: str,
    blocks_df: pd.DataFrame,
) -> tuple[pd.DataFrame, str]:
    """Run baseline or transformer inference based on available artifacts."""
    if model_choice == "baseline":
        baseline_bundle = find_latest_baseline_artifacts()
        if baseline_bundle is None:
            raise FileNotFoundError("Baseline model selection is unavailable because no saved baseline artifact was found.")
        return run_baseline_inference(baseline_bundle.model_path, blocks_df), baseline_bundle.source

    if model_choice == "transformer":
        transformer_bundle = find_latest_transformer_artifacts()
        if transformer_bundle is None:
            raise FileNotFoundError("Transformer model selection is unavailable because no saved transformer artifact was found.")
        artifacts = load_transformer_artifacts(
            checkpoint_dir=transformer_bundle.checkpoint_dir,
            tokenizer_dir=transformer_bundle.tokenizer_dir,
            label_mapping_path=transformer_bundle.label_mapping_path,
        )
        return run_transformer_inference(blocks_df=blocks_df, artifacts=artifacts), transformer_bundle.source

    raise ValueError(f"Unsupported model choice: {model_choice}")


def _process_pdf(
    document_input: DocumentInput,
    profile_path: str | Path,
) -> ProcessingArtifacts:
    """PDF audit-only branch (REQ-pdf-text-only, D-02 SVM bypass).

    Per 07-CONTEXT.md D-03: text-layer ratio < 0.50 raises PdfNoTextLayer,
    which app.run_processing catches and routes to preflight_translate_error.
    Per D-02: SVM + rule engine bypassed entirely; every block is
    status="review". Per D-PDF-SCOPE: output_docx is always None.
    Per OQ-1 (07-RESEARCH.md): NO separate predictions CSV is emitted —
    predictions_csv field is set to the report_csv path as a sentinel
    (single existing artefact, four-artefact shape preserved without
    emitting an empty file).
    """
    ratio = check_text_layer(document_input.path)
    if ratio < 0.50:
        raise PdfNoTextLayer("PDF text-layer ratio below 0.50 threshold")

    timestamp = _timestamp()
    stem = document_input.path.stem
    report_csv = REPORTS_DIR / f"{stem}_audit_{timestamp}.csv"

    rows = extract_pdf_blocks(document_input.path)
    report_df = pd.DataFrame(rows)
    # Ensure DOCX-compatible 17-column schema — missing columns -> None/empty.
    for col in (
        "label", "action", "profile_id", "profile_name",
        "confidence_score", "low_confidence", "manual_review_required",
        "blocked_unsafe_autofix", "unsafe_auto_fix_reason",
        "violated_rules", "suggested_rule_ids", "suggested_fix",
        "changed_fields", "uncertain_fields", "reason", "recommendation",
    ):
        if col not in report_df.columns:
            report_df[col] = None
    report_df.to_csv(report_csv, index=False, encoding="utf-8-sig")

    review_count = int((report_df["status"] == "review").sum())
    summary: dict[str, Any] = {
        "model_type": "pdf_audit",
        "mode": "audit",
        "profile_name": None,
        "profile_id": None,
        "blocks_total": len(report_df),
        "review": review_count,
        "no_change": 0,
        "changed": 0,
        "error": 0,
        "blocked_unsafe_autofix": 0,
        "output_docx": None,
    }
    report_json, summary_json, summary_txt = _save_run_sidecars(
        timestamp=timestamp, report_df=report_df, summary=summary
    )

    return ProcessingArtifacts(
        model_type="pdf_audit",
        mode="audit",
        profile_path=Path(profile_path),
        input_path=document_input.path,
        input_extension=".pdf",
        extracted_csv=report_csv,    # OQ-1: no separate extracted artefact for PDF
        predictions_csv=report_csv,  # OQ-1: no separate predictions artefact — sentinel
        report_csv=report_csv,
        report_json=report_json,
        summary_json=summary_json,
        summary_txt=summary_txt,
        output_docx=None,
        predictions_df=pd.DataFrame(),
        report_df=report_df,
        summary=summary,
    )


def process_document(
    input_path: str | Path,
    model_choice: str,
    mode: str,
    profile_path: str | Path,
) -> ProcessingArtifacts:
    """Run the complete processing flow (DOCX audit/fix or PDF audit-only)."""
    ensure_runtime_directories()
    document_input = validate_document_input(input_path)

    if document_input.extension == ".pdf":
        return _process_pdf(document_input=document_input, profile_path=profile_path)

    blocks_df = extract_blocks_from_docx(document_input.path)
    if blocks_df.empty:
        raise ValueError("The input DOCX does not contain any extractable non-empty blocks.")

    predictions_df, artifact_source = _run_model_inference(model_choice=model_choice, blocks_df=blocks_df)

    timestamp = _timestamp()
    stem = document_input.path.stem
    extracted_csv = EXTRACTED_DIR / f"{stem}_blocks_{timestamp}.csv"
    predictions_csv = PREDICTIONS_DIR / f"{stem}_{model_choice}_predictions_{timestamp}.csv"
    report_csv = REPORTS_DIR / f"{stem}_{mode}_audit_{timestamp}.csv"
    output_docx = None
    if mode == "fix":
        output_docx = GENERATED_DOCX_DIR / f"{stem}_{model_choice}_formatted_{timestamp}.docx"

    blocks_df.to_csv(extracted_csv, index=False, encoding="utf-8-sig")
    predictions_df.to_csv(predictions_csv, index=False, encoding="utf-8-sig")

    summary = audit_or_format_docx(
        input_docx=document_input.path,
        predictions_csv=predictions_csv,
        report_csv=report_csv,
        output_docx=output_docx,
        apply_safe=(mode == "fix"),
        profile_path=profile_path,
    )
    summary["model_type"] = model_choice
    summary["artifact_source"] = artifact_source

    report_df = pd.read_csv(report_csv)
    report_json, summary_json, summary_txt = _save_run_sidecars(timestamp=timestamp, report_df=report_df, summary=summary)

    return ProcessingArtifacts(
        model_type=model_choice,
        mode=mode,
        profile_path=Path(profile_path),
        input_path=document_input.path,
        input_extension=".docx",
        extracted_csv=extracted_csv,
        predictions_csv=predictions_csv,
        report_csv=report_csv,
        report_json=report_json,
        summary_json=summary_json,
        summary_txt=summary_txt,
        output_docx=output_docx,
        predictions_df=predictions_df,
        report_df=report_df,
        summary=summary,
    )
